# Generated by Django 4.1 on 2022-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customusermodel",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
